name: Reconstruct

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  reconstruct:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git python3 python3-venv build-essential pkg-config \
            libasound2-dev libx11-dev libfreetype6-dev libgl1-mesa-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libxss-dev libxkbcommon-dev libpulse-dev libssl-dev

      - name: Run conversation parser
        run: |
          python3 -m venv .venv || true
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 tools/parse_convos.py --input-dir . --output-dir reconstructed --report INTEGRATION_REPORT.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add reconstructed/ INTEGRATION_REPORT.md || true
            git commit -m "Reconstruct files from convo-*.txt" || true
            git push origin main || true
          fi

      - name: Configure and build JUCE project
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DJUCE_TAG=master ..
          cmake --build . --config Release -- -j$(nproc)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: juce-build
          path: build/
